# coding: utf-8

"""
    Golf v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fantasy_data_golf_api
from fantasy_data_golf_api.api.default_api import DefaultApi  # noqa: E501
from fantasy_data_golf_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = fantasy_data_golf_api.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dfs_slates(self):
        """Test case for dfs_slates

        DFS Slates  # noqa: E501
        """
        pass

    def test_injuries(self):
        """Test case for injuries

        Injuries  # noqa: E501
        """
        pass

    def test_injuries_historical(self):
        """Test case for injuries_historical

        Injuries (Historical)  # noqa: E501
        """
        pass

    def test_leaderboard(self):
        """Test case for leaderboard

        Leaderboard  # noqa: E501
        """
        pass

    def test_news(self):
        """Test case for news

        News  # noqa: E501
        """
        pass

    def test_news_by_date(self):
        """Test case for news_by_date

        News by Date  # noqa: E501
        """
        pass

    def test_news_by_player(self):
        """Test case for news_by_player

        News by Player  # noqa: E501
        """
        pass

    def test_player(self):
        """Test case for player

        Player  # noqa: E501
        """
        pass

    def test_player_season_stats_w_world_golf_rankings(self):
        """Test case for player_season_stats_w_world_golf_rankings

        Player Season Stats (w/ World Golf Rankings)  # noqa: E501
        """
        pass

    def test_player_tournament_projected_stats_w_draftkings_salaries(self):
        """Test case for player_tournament_projected_stats_w_draftkings_salaries

        Player Tournament Projected Stats (w/ DraftKings Salaries)  # noqa: E501
        """
        pass

    def test_player_tournament_stats_by_player(self):
        """Test case for player_tournament_stats_by_player

        Player Tournament Stats By Player  # noqa: E501
        """
        pass

    def test_players(self):
        """Test case for players

        Players  # noqa: E501
        """
        pass

    def test_schedule(self):
        """Test case for schedule

        Schedule  # noqa: E501
        """
        pass

    def test_schedule_by_season(self):
        """Test case for schedule_by_season

        Schedule by Season  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
