# coding: utf-8

"""
    Golf v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fantasy_data_golf_api
from fantasy_data_golf_api.models.dfs_slate_player import DfsSlatePlayer  # noqa: E501
from fantasy_data_golf_api.rest import ApiException


class TestDfsSlatePlayer(unittest.TestCase):
    """DfsSlatePlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDfsSlatePlayer(self):
        """Test DfsSlatePlayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fantasy_data_golf_api.models.dfs_slate_player.DfsSlatePlayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
