# coding: utf-8

"""
    Golf v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fantasy_data_golf_api
from fantasy_data_golf_api.models.player_tournament_projection import PlayerTournamentProjection  # noqa: E501
from fantasy_data_golf_api.rest import ApiException


class TestPlayerTournamentProjection(unittest.TestCase):
    """PlayerTournamentProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerTournamentProjection(self):
        """Test PlayerTournamentProjection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fantasy_data_golf_api.models.player_tournament_projection.PlayerTournamentProjection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
