# coding: utf-8

# flake8: noqa
"""
    Golf v2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from fantasy_data_golf_api.models.dfs_slate import DfsSlate
from fantasy_data_golf_api.models.dfs_slate_player import DfsSlatePlayer
from fantasy_data_golf_api.models.dfs_slate_tournament import DfsSlateTournament
from fantasy_data_golf_api.models.injury import Injury
from fantasy_data_golf_api.models.leaderboard import Leaderboard
from fantasy_data_golf_api.models.news import News
from fantasy_data_golf_api.models.player import Player
from fantasy_data_golf_api.models.player_hole import PlayerHole
from fantasy_data_golf_api.models.player_round import PlayerRound
from fantasy_data_golf_api.models.player_season import PlayerSeason
from fantasy_data_golf_api.models.player_tournament import PlayerTournament
from fantasy_data_golf_api.models.player_tournament_projection import PlayerTournamentProjection
from fantasy_data_golf_api.models.round import Round
from fantasy_data_golf_api.models.tournament import Tournament
